### ISSUE TITLE
SEU MERDA

### ISSUE THREAD

**Issue by RshaCuDeVidro** [0xDetrew/Dotfiles#1]
TA TUDO ERRADO AS CONFIG KKKKKKKKKK
KILL NO WIN+W VAI SE FUDER KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

**Comment by 0xDetrew** [comment]
te amo maninho <3 obrg
